[system]
g=9.81
timedelta=0.01
steps=8000
filename="smalloscillation"

    [[system.pendula]]
    length=10
    mass=1
    theta=[0.1,"p"]
    phi=[0,"r"]
    thetadot=[0,"r"]
    phidot=[0,"r"]
    zPole=true

