[system]
#filename to gather data from (previously simulated pickle)
filename="smalloscillation"
#whether to give a 2D diagnostic plot (false), or a 3D animated plot (true)
anim=false
    [system.plot]
    # cartesian position
    x = [true, true, true]
    # cartesian velocity
    v = [false, false, false]
    #angles [theta, phi]
    pos = [false, false]
    #angular speeds [thetadot, phidot]
    vel = [false, false]
    #coordinate basis
    pole = false
    #kinetic, potential, and mechanical energy for a given pendulum
    KE = false
    PE = false
    ME = false
    #total kinetic, potential, and mechanical energy for the entire system
    totalKE = false
    totalPE = false
    totalME = false
    #cartesian linear momentum and angular momentum for each pendulum
    LM = [false, false, false]
    AM = [false, false, false]
    #absolute linear momentum and angular momentum for each pendulum
    absLM = false
    absAM = false
    #total cartesian linear momentum and angular momentum for the entire system
    totalLM = [false, false, false]
    totalAM = [false, false, false]
    #magnitude of the total linear momentum and angular momentum of
    #the entire system
    absTotalLM = false
    absTotalAM = false
    #sum of the magnitudes of the linear and angular momentum of each pendulum
    totalAbsLM = false
    totalAbsAM = false